
###
GET http://localhost:3000/pet/
Content-Type: application/json
Origin: http://localhost:5173

### Get single pet by userId
GET http://localhost:3000/pet/68d56b6ece298c0acb9d3a2d
Origin: http://localhost:5173


### Update pet activity 
POST http://localhost:3000/pet/68d40ebacee12500a157aa69/activity
Content-Type: application/json
Origin: http://localhost:5173

{
  "activity": "feed"
}